version: "3"

services:
  client:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    volumes:
      - .:/home/oauth
    environment:
      - SECRET_KEY=yLxbyA1Vo0MBPV4CYmoUBsqYnxh8ygwW
      - UWSGI_INI=/home/oauth/client/uwsgi.ini
      - LISTEN_PORT=10000
    restart: always
  
  auth_server:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10001:10001
    volumes:
      - .:/home/oauth
    environment:
      - SECRET_KEY=yLxbyA1Vo0MBPV4CYmoUBsqYnxh8ygwW
      - UWSGI_INI=/home/oauth/authorizationServer/uwsgi.ini
      - LISTEN_PORT=10001
    restart: always

  protected_resource:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10002:10002
    volumes:
      - .:/home/oauth
    environment:
      - SECRET_KEY=yLxbyA1Vo0MBPV4CYmoUBsqYnxh8ygwW
      - UWSGI_INI=/home/oauth/protectedResource/uwsgi.ini
      - LISTEN_PORT=10002
    restart: always

  exploit:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10003:10003
    volumes:
      - .:/home/oauth
    environment:
      - UWSGI_INI=/home/oauth/exploit/uwsgi.ini
      - LISTEN_PORT=10003
    restart: always